#!/usr/bin/env bash
# train/start_pipeline.sh — Start or resume the iris training pipeline orchestrator.
#
# Usage:
#   ./train/start_pipeline.sh
#   ./train/start_pipeline.sh --data-root /Volumes/2TBSSD
#   ./train/start_pipeline.sh --config train/configs/v2_pipeline_smoke.yaml
#   ./train/start_pipeline.sh --data-root /Volumes/2TBSSD/dev --config train/configs/v2_pipeline_dev.yaml
#
# Config selection order (if --config not given):
#   1. train/configs/v2_pipeline_active.yaml  (generated by pipeline_setup.py for custom scales)
#   2. train/configs/v2_pipeline.yaml         (default small/medium/large/all-in config)
#
# PIPELINE_DATA_ROOT defaults to /Volumes/2TBSSD if not set in the environment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$SCRIPT_DIR/.venv/bin/python"
PIPELINE_CTL="$SCRIPT_DIR/scripts/pipeline_ctl.py"
PIPELINE_STATUS="$SCRIPT_DIR/scripts/pipeline_status.py"
CONFIGS_DIR="$SCRIPT_DIR/configs"

DATA_ROOT="${PIPELINE_DATA_ROOT:-/Volumes/2TBSSD}"
CONFIG=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --data-root) DATA_ROOT="$2"; shift 2 ;;
        --config)    CONFIG="$2";    shift 2 ;;
        -h|--help)
            sed -n '2,14p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# Config resolution
if [[ -z "$CONFIG" ]]; then
    if [[ -f "$CONFIGS_DIR/v2_pipeline_active.yaml" ]]; then
        CONFIG="$CONFIGS_DIR/v2_pipeline_active.yaml"
    else
        CONFIG="$CONFIGS_DIR/v2_pipeline.yaml"
    fi
fi

# Sanity checks
if [[ ! -f "$VENV" ]]; then
    echo "ERROR: venv not found at $SCRIPT_DIR/.venv" >&2
    echo "Run: cd train && python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt" >&2
    exit 1
fi
if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: config not found: $CONFIG" >&2
    exit 1
fi
if [[ ! -d "$DATA_ROOT" ]]; then
    echo "ERROR: DATA_ROOT not found: $DATA_ROOT" >&2
    exit 1
fi

echo "data root : $DATA_ROOT"
echo "config    : $CONFIG"
echo ""

# Show current state before touching anything
PIPELINE_DATA_ROOT="$DATA_ROOT" "$VENV" "$PIPELINE_STATUS" 2>/dev/null || true
echo ""

# Start (or restart) the orchestrator in the iris tmux session.
# pipeline_ctl creates the session if it does not exist.
PIPELINE_DATA_ROOT="$DATA_ROOT" "$VENV" "$PIPELINE_CTL" restart-orchestrator --config "$CONFIG"

echo ""
echo "Watch:  tmux attach -t iris"
echo "Status: PIPELINE_DATA_ROOT=$DATA_ROOT $VENV $PIPELINE_STATUS"
