#!/usr/bin/env bash
# train/start_pipeline.sh — Start or resume the iris training pipeline orchestrator.
#
# Usage:
#   ./train/start_pipeline.sh
#   ./train/start_pipeline.sh --data-root /Volumes/2TBSSD
#   ./train/start_pipeline.sh --config train/configs/v2_pipeline_smoke.yaml
#   ./train/start_pipeline.sh --data-root /Volumes/2TBSSD/dev --config train/configs/v2_pipeline_dev.yaml
#
# Config selection order (if --config not given):
#   1. train/configs/v2_pipeline_active.yaml  (generated by pipeline_setup.py for custom scales)
#   2. Prompt to run pipeline_setup.py        (no active config — first-time setup)
#
# PIPELINE_DATA_ROOT defaults to /Volumes/2TBSSD if not set in the environment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$SCRIPT_DIR/.venv/bin/python"
PIPELINE_CTL="$SCRIPT_DIR/scripts/pipeline_ctl.py"
PIPELINE_SETUP="$SCRIPT_DIR/scripts/pipeline_setup.py"
PIPELINE_STATUS="$SCRIPT_DIR/scripts/pipeline_status.py"
CONFIGS_DIR="$SCRIPT_DIR/configs"

DATA_ROOT="${PIPELINE_DATA_ROOT:-/Volumes/2TBSSD}"
CONFIG=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --data-root) DATA_ROOT="$2"; shift 2 ;;
        --config)    CONFIG="$2";    shift 2 ;;
        -h|--help)
            sed -n '2,13p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# Venv check first — needed for both setup and start
if [[ ! -f "$VENV" ]]; then
    echo "ERROR: venv not found at $SCRIPT_DIR/.venv" >&2
    echo "Run: cd train && python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt" >&2
    exit 1
fi

# Config resolution
if [[ -z "$CONFIG" ]]; then
    if [[ -f "$CONFIGS_DIR/v2_pipeline_active.yaml" ]]; then
        CONFIG="$CONFIGS_DIR/v2_pipeline_active.yaml"
    else
        # No active config — this looks like a first-time run.
        # Offer to run the setup wizard rather than silently using the default.
        echo "No active pipeline config found (train/configs/v2_pipeline_active.yaml)."
        echo ""
        echo "This is typically a first-time setup. The setup wizard will:"
        echo "  - Let you choose a run scale (dev/smoke/small/medium/large/all-in)"
        echo "  - Configure quality features (SigLIP, hard-example mining, dedup)"
        echo "  - Validate prerequisites and create required directories"
        echo "  - Generate the config and print exact start/stop commands"
        echo ""
        read -r -p "Run setup wizard now? [Y/n] " _answer
        _answer="${_answer:-Y}"
        if [[ "$_answer" =~ ^[Yy] ]]; then
            PIPELINE_DATA_ROOT="$DATA_ROOT" "$VENV" "$PIPELINE_SETUP" --data-root "$DATA_ROOT"
            echo ""
            # Setup wizard may have written v2_pipeline_active.yaml
            if [[ -f "$CONFIGS_DIR/v2_pipeline_active.yaml" ]]; then
                CONFIG="$CONFIGS_DIR/v2_pipeline_active.yaml"
            else
                # Setup chose a built-in config (dev/smoke); user sees the exact command to use
                echo "Setup complete. Use the start command printed above."
                exit 0
            fi
        else
            CONFIG="$CONFIGS_DIR/v2_pipeline.yaml"
            echo "Using default config: $CONFIG"
        fi
    fi
fi

if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: config not found: $CONFIG" >&2
    exit 1
fi
if [[ ! -d "$DATA_ROOT" ]]; then
    echo "ERROR: DATA_ROOT not found: $DATA_ROOT" >&2
    exit 1
fi

echo "data root : $DATA_ROOT"
echo "config    : $CONFIG"
echo ""

# Show current state before touching anything
PIPELINE_DATA_ROOT="$DATA_ROOT" "$VENV" "$PIPELINE_STATUS" 2>/dev/null || true
echo ""

# Start (or restart) the orchestrator in the iris tmux session.
# pipeline_ctl creates the session if it does not exist.
PIPELINE_DATA_ROOT="$DATA_ROOT" "$VENV" "$PIPELINE_CTL" restart-orchestrator --config "$CONFIG"

echo ""
echo "Watch:  tmux attach -t iris"
echo "Status: PIPELINE_DATA_ROOT=$DATA_ROOT $VENV $PIPELINE_STATUS"
